function paths = get_full_paths( contents )

assert( istable( contents ) );

paths = cellfun( ...
    @fullfile, ...
    contents.folder, ...
    contents.name, ...
    'uniformoutput', false ...
    );
paths = string( paths );

end

